FROM node:22.3.0-alpine

# Set evironment variables.
ENV LANG=C.UTF-8

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY ./mountains/package.json . 

# Install packages.
RUN npm i

# Copy directory.
COPY ./mountains .

# Document exposed port.
EXPOSE ${REACT_PORT}

# Start app.
CMD ["npm", "start"]